### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by rherrick** [hzub/demo-ci-cd#1]
I've tried with a few different versions of node (8.15.1, 10.15.3, 11.12.0) and on OS X and Ubuntu. Same error every time:

`> @ dev /Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd
> webpack-dev-server --content-base=./src/ --inline --hot

/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/webpack.config.js:25
      ENVIRONMENT: JSON.stringify(env.environment)
                                      ^

TypeError: Cannot read property 'environment' of undefined
    at module.exports.env (/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/webpack.config.js:25:39)
    at handleFunction (/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/node_modules/webpack-cli/bin/prepareOptions.js:21:13)
    at prepareOptions (/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/node_modules/webpack-cli/bin/convert-argv.js:118:14)
    at /Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at Object.<anonymous> (/Users/rherrick/Development/XNAT/Tools/Clients/XNAT-App/demo-ci-cd/node_modules/webpack-dev-server/bin/webpack-dev-server.js:87:55)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

I put the full output and generated logs [here](https://gist.github.com/rherrick/796389d50da62a1238a2ac7b2556fa2b).

**Comment by hzub** [comment]
Oh my! @rherrick thanks for reporting, erroneous version of package.json somehow made it to the final branch. 
Issue was fixed with commit 7f11fe7. 
Thanks again!
